server:
  port: 7100

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

coordinator:
  api:
    host: ${COORDINATOR_HOST:http://localhost}
    port: ${COORDINATOR_PORT:7000}
    addresses: /coordinator/command/instance/info/

spark:
  home: ${SPARK_HOME:/home/mmarkiew/dev/spark}
  master-host:
  master-port: 7077
  driver-port: 11000
  block-manager-port: 12000

# TODO AppAlgorithmsConfig include as dependency and run
apps:
  runner:
    path: /home/mmarkiew/stud/ddm-platform/platform/app-runner-java/build/libs/app-runner-java-0.0.1-SNAPSHOT-all.jar
    main-class: pl.edu.pw.ddm.platform.runner.CentralRunner
  algorithms:
    - /home/mmarkiew/stud/ddm-platform/platform/algorithms/clustering/aoptkm/build/libs/aoptkm-1.0-SNAPSHOT-all.jar

paths:
  root: /ddm
  datasets: ${paths.root}/datasets
  distance-functions:
    path: ${paths.root}/distance_functions
    desc-filename: desc.properties
  algorithms:
    path: ${paths.root}/algorithms
    desc-filename: desc.properties
  execution:
    path: ${paths.root}/execution
# vvv   don't change as ControlFileNames is source of truth vvv
    status-filename: status.json
    results:-filename: results.txt
    statistics-filename: stats.json
# ^^^   don't change as ControlFileNames is source of truth ^^^
    logs:
      central-filename: central.log
      spark-work-dir: /spark/work
