server:
  port: 7000

spring:
  profiles:
    active: instance-local-docker
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

paths:
  root: ${java.io.tmpdir}/coordinator
  algorithms: ${paths.root}/algorithms
  distance-functions: ${paths.root}/distance_functions
  partitioner-strategies: ${paths.root}/partitioner_strategies
  datasets: ${paths.root}/datasets
  logs:
    path: ${paths.root}/logs
    node-file-suffix: .log
  results:
    path: ${paths.root}/results
    archive-path: ${paths.root}/archive_results
    node-filename-suffix: -results.txt
    stats-filename: stats.json
    validation-filename: validation.json
    execution-desc-filename: description.properties

communiaction:
  node-agent-port: 7100
  spark:
    master-port: 7077
    master-ui-port: 8080
    worker-ui-port: 8081
